image: maven:3.9.6-eclipse-temurin-17

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

cache:
  key:
    files:
      - pom.xml
  paths:
    - .m2/repository

stages:
  - compile
  - test

# ------------------------------------------
# STAGE 1: COMPILAR CÓDIGO Y GENERAR FUENTES
# ------------------------------------------
compile_job:
  stage: compile
  script:
    - echo "🛠️ Compilando pedidos-backend..."
    - mvn clean compile -DskipTests
  artifacts:
    paths:
      - target/generated-sources/openapi/
      - target/classes/
    expire_in: 1 hour

# ------------------------------------------
# STAGE 2: EJECUTAR PRUEBAS UNITARIAS
# ------------------------------------------
test_job:
  stage: test
  dependencies:
    - compile_job
  script:
    - echo "🧪 Ejecutando la suite de pruebas unitarias de pedidos-backend..."
    - mvn test
  artifacts:
    when: always
    reports:
      junit: target/surefire-reports/TEST-*.xml
